name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm check-types

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build check
        run: pnpm build:local
        env:
          SKIP_ENV_VALIDATION: true

      - name: Verify MCP tool loading
        run: pnpm test agent-tool-loading.test.ts
